// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SharpKnowledge.Data;

#nullable disable

namespace SharpKnowledge.Data.Migrations
{
    [DbContext(typeof(PostgreContext))]
    [Migration("20250928120424_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SharpKnowledge.Data.Models.BrainModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("BestScore")
                        .HasColumnType("real");

                    b.Property<float[,]>("Biases")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.Property<string>("BrainType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Generation")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("TotalRuns")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("BrainModels");
                });

            modelBuilder.Entity("SharpKnowledge.Data.Models.Weight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("BrainModelId")
                        .HasColumnType("uuid");

                    b.Property<float[,]>("WeightData")
                        .IsRequired()
                        .HasColumnType("real[]");

                    b.HasKey("Id");

                    b.HasIndex("BrainModelId");

                    b.ToTable("Weight");
                });

            modelBuilder.Entity("SharpKnowledge.Data.Models.Weight", b =>
                {
                    b.HasOne("SharpKnowledge.Data.Models.BrainModel", null)
                        .WithMany("WeightsCollection")
                        .HasForeignKey("BrainModelId");
                });

            modelBuilder.Entity("SharpKnowledge.Data.Models.BrainModel", b =>
                {
                    b.Navigation("WeightsCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
